sonar.projectKey=paaradox-labs_dist-auth-service
sonar.organization=paaradox-labss

sonar.projectName=dist-auth-service


sonar.sources=src

sonar.tests=tests

sonar.exclusions=**/node_modules/**/*, **/dist/**/*, **/build/**/*, **/migration/**/*

sonar.qualitygate.wait=true

sonar.javascript.lcov.reportPaths=./coverage/lcov.info

sonar.scm.exclusions.disabled=true